// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Use direct URL for CLI operations (migrations, db push)
    // PrismaClient in code will use DATABASE_URL (pooler) via constructor
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
